version: '3'

networks: 
    laravel:
        driver: bridge

services: 
    nginx:
        image: nginx:alpine
        container_name: "${CONTAINER_PREFIX}_nginx"
        restart: unless-stopped
        tty: true
        ports:
            - "8000:8000"
        volumes: 
            - ./src:/var/www/app
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on: 
            - php
            - postgres
        networks: 
            - laravel

    postgres:
        image: postgres:alpine
        container_name: "${CONTAINER_PREFIX}_postgres"
        restart: unless-stopped
        tty: true
        ports:
            - "5432:5432"
        volumes:
            - ./postgresql:/var/lib/postgresql/data
        env_file:
            - .env
        networks:
            - laravel

    php:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel_docker:latest
        container_name: "${CONTAINER_PREFIX}_php"
        restart: unless-stopped
        tty: true
        working_dir: /var/www/app
        volumes: 
            - ./src:/var/www/app
        ports: 
            - "9000:9000"
        networks: 
            - laravel

    redis:
        image: redis:alpine
        container_name: "${CONTAINER_PREFIX}_redis"
        ports:
            - "6379:6379"
        networks:
            - laravel